version: "3.6"

services:

    main:
        build:
            context: ./main
            dockerfile: Dockerfile
        image: klleon:main
        ports:
            - "8000:8000"

    separate:
        build:
            context: ./separate
            dockerfile: Dockerfile
        image: klleon:separate
        ports:
            - "7000:7000"
