version: "3.6"

services:

  main:
    build:
      context: ./main_temp
      dockerfile: Dockerfile
    image: klleon:main_temp
    ports:
      - "8000:8000"
    environment:
      - SEP_API_URL=http://separate:7000/separate
      - COLLECTION_NAME=klleon
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  separate:
    build:
      context: ./separate_temp
      dockerfile: Dockerfile
    image: klleon:separate_temp
    ports:
      - "7000:7000"
    environment:
      - SEP_API_URL=http://separate:7000/separate
      - COLLECTION_NAME=klleon
      - BUCKET_NAME=klleon-output
    command: uvicorn main:app --host 0.0.0.0 --port 7000
