steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/klleon:separate', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/klleon:separate']
timeout: 1200s
options:
  machineType: 'N1_HIGHCPU_8'
